# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: |
        cd betbot
        docker build . --tag nickpyren/betbot:latest
        
    - name: Push the latest Docker image
      run: docker push nickpyren/betbot:latest
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-1-16-6-do-2-tor1-betbot

    - name: Deploy to DigitalOcean Kubernetes
      run: |
        sed 's/{{DISCORD_TOKEN}}/${{ secrets.DISCORD_TOKEN }}/' $GITHUB_WORKSPACE/config/deployment-template.yml > $GITHUB_WORKSPACE/config/deployment.yml
        kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml

    - name: Verify deployment
      run: kubectl rollout status deployment/betbot
